import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Generate idempotent seed SQL from the knowledge base (ontology + plays), so
 * seeding can run through any plain-SQL channel (Supabase SQL editor, the
 * Management API via scripts/db-remote.ts, or psql).
 *
 * Output: supabase/seed/0001_knowledge.sql
 */

function q(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function jsonLiteral(value: unknown): string {
  const json = JSON.stringify(value);
  if (json.includes("$json$")) throw new Error("json contains dollar-quote delimiter");
  return `$json$${json}$json$::jsonb`;
}

function main() {
  const ontology = JSON.parse(
    readFileSync(join(process.cwd(), "knowledge", "ontology", "core.json"), "utf8"),
  ) as {
    nodes: { slug: string; name: string; parent: string | null }[];
    edges: { from: string; to: string; type: string; weight: number }[];
  };

  const lines: string[] = [
    "-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.",
    "-- Idempotent seed of the Channel Knowledge Base (ontology + play templates).",
    "begin;",
  ];

  for (const n of ontology.nodes) {
    lines.push(
      `insert into taxonomy_nodes (slug, name) values (${q(n.slug)}, ${q(n.name)})` +
        ` on conflict (slug) do update set name = excluded.name;`,
    );
  }
  for (const n of ontology.nodes) {
    if (!n.parent) continue;
    lines.push(
      `update taxonomy_nodes set parent_id = (select id from taxonomy_nodes where slug = ${q(n.parent)})` +
        ` where slug = ${q(n.slug)};`,
    );
  }
  for (const e of ontology.edges) {
    lines.push(
      `insert into taxonomy_edges (from_node_id, to_node_id, edge_type, weight)` +
        ` values ((select id from taxonomy_nodes where slug = ${q(e.from)}),` +
        ` (select id from taxonomy_nodes where slug = ${q(e.to)}), ${q(e.type)}, ${e.weight})` +
        ` on conflict (from_node_id, to_node_id, edge_type) do update set weight = excluded.weight;`,
    );
  }

  const playsDir = join(process.cwd(), "knowledge", "plays");
  for (const file of readdirSync(playsDir).filter((f) => f.endsWith(".json"))) {
    const play = JSON.parse(readFileSync(join(playsDir, file), "utf8")) as {
      slug: string;
      version: number;
      name: string;
      taxonomy_node: string;
    };
    lines.push(
      `insert into play_templates (slug, version, name, taxonomy_node_id, definition)` +
        ` values (${q(play.slug)}, ${play.version}, ${q(play.name)},` +
        ` (select id from taxonomy_nodes where slug = ${q(play.taxonomy_node)}), ${jsonLiteral(play)})` +
        ` on conflict (slug, version) do update set name = excluded.name,` +
        ` taxonomy_node_id = excluded.taxonomy_node_id, definition = excluded.definition;`,
    );
  }

  lines.push("commit;");
  const out = join(process.cwd(), "supabase", "seed", "0001_knowledge.sql");
  writeFileSync(out, lines.join("\n") + "\n");
  console.log(`wrote ${out} (${lines.length} statements)`);
}

main();
